[package]
name = "timed-queue"
version = "0.1.0"
authors = ["Brennan Vincent <brennan@umanwizard.com>"]
edition = "2018"
license = "MIT"
description = "(placeholder)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
